version : "3.7"
services:
  database:
    image: mysql:8.0.36
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: jack0366!
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: lighthouse_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/test?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: jack0366!
    networks:
      - springboot-mysql-net
networks:
  springboot-mysql-net:
    driver: bridge
